# Generated by Django 5.0.7 on 2024-08-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('location_link', models.TextField()),
                ('menu_offering', models.TextField()),
                ('payment_options', models.TextField()),
                ('menu_name', models.TextField()),
                ('menu_href', models.TextField()),
                ('dietary_options', models.TextField()),
                ('opening_days', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
