# Generated by Django 5.0.7 on 2024-09-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YorkEats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(default='No address found', null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.TextField(default='#', null=True),
        ),
    ]
