# Generated by Django 5.0.7 on 2024-08-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YorkEats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
