# Generated by Django 5.0.7 on 2024-08-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YorkEats', '0003_place_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
